# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
