# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_remove_modelo_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
